### ISSUE TITLE
EndorsementPlugin 怎么获取？

### ISSUE THREAD

**Issue by fuyi501** [xuperchain/xuper-sdk-js#21]
在 js 中如何获取 这个插件？

直接使用会报 not defined 错误

![image](https://user-images.githubusercontent.com/20770905/153551166-d99931b6-1476-4488-924b-bac4b0ac8aa7.png)

**Comment by fuyi501** [comment]
自己解答吧

import { Endorsement } from '@xuperchain/xuper-sdk'

**Comment by uaanaa** [comment]
const {default:XuperSDK,Endorsement} = require("@xuperchain/xuper-sdk")
