### ISSUE TITLE
开放网络获取到的数据如何解密？

### ISSUE THREAD

**Issue by fuyi501** [xuperchain/xuper-sdk-js#22]
我使用 js 连接 开放网络，获取到数据，但获取到的数据都是加密后的数据，如何解密相应的数据？

如下图是获取到的加密后的数据：

<img width="565" alt="image" src="https://user-images.githubusercontent.com/20770905/153569954-cef4f48d-c3a7-4329-889b-55784bb2c77b.png">

我通过在 Xuper 控制中心获取到的数据如下：

<img width="557" alt="image" src="https://user-images.githubusercontent.com/20770905/153570185-72bfb8cb-b19c-47b2-9747-1cc7e838037a.png">

如何将加密的数据解析成正常数据？

**Comment by fuyi501** [comment]
也自己解答下

base64 编码的

**Comment by uaanaa** [comment]
嗯 base64 编码的
