### ISSUE TITLE
如何获取交易hash？

### ISSUE THREAD

**Issue by fuyi501** [xuperchain/xuper-sdk-js#24]
**我使用的是超级链的开放网络，连接的 文件hash 智能合约，我在执行存储文件 `storeFileInfo` 合约方法后，尝试去查询这个交易记录获取他的交易 hash（执行合约方法后没找到交易hash，只获取到一个 txid ）**

![image](https://user-images.githubusercontent.com/20770905/154184700-12560d23-93a9-4f99-a11f-08a49e8bd0da.png)

**我尝试使用 `xsdk.queryTransaction(txid)` 这个方法获取详细的交易信息，看是否可以获取到 `交易hash`，执行之后输出如下：**

![image](https://user-images.githubusercontent.com/20770905/154184937-62e585c8-0173-44d0-83d3-c315602cbdf2.png)

**好像还是没有 `交易hash`，但是获取到一个 `blockid`，再尝试使用` xsdk.getBlockById(blockid) `这个方法获取区块信息：**

**通过交易获取到的 `blockid` 为 `vCd/DO/GVsL28MrqljpyB5Dhl3CM+cofvU8J5XJFbuc=` ，但是使用这个 id 获取不到区块信息：**

![image](https://user-images.githubusercontent.com/20770905/154185284-f51d5a3b-5b67-448e-afe7-b789e4e2b0cf.png)

**这时候发现有个 `xsdk.transactionIdToHex('vCd/DO/GVsL28MrqljpyB5Dhl3CM+cofvU8J5XJFbuc=')` 转 hex 的方法，于是把 blockid 进行了转换：**

```sh
xsdk.transactionIdToHex('vCd/DO/GVsL28MrqljpyB5Dhl3CM+cofvU8J5XJFbuc=')
# 输出：bc277f0cefc656c2f6f0caea963a720790e197708cf9ca1fbd4f09e572456ee7
```

**再用 `bc277f0cefc656c2f6f0caea963a720790e197708cf9ca1fbd4f09e572456ee7` 来查询 区块信息：**

```
await xsdk.getBlockById('bc277f0cefc656c2f6f0caea963a720790e197708cf9ca1fbd4f09e572456ee7')
```

**输出：**

![image](https://user-images.githubusercontent.com/20770905/154186015-4747f170-887a-4d02-92c1-d9dc07a2f119.png)

**确实获取到了区块信息，说明 ` xsdk.getBlockById(blockid) ` 这个方法不能直接根据 id 获取，需要先把 blockid 进行 hex 转换之后才行？这是不是不太合理？**

**另外就是：怎么获取 交易hash ？**

**Comment by SmilingXinyi** [comment]
1. blockid是将数据直接返回了呢，也许这确实不是一个好的体验，后面的开发中会考虑进行完善；可以先将此函数封装使用
2. 交易 hash 的字段是 txid
