### ISSUE TITLE
postTransaction 的 交易 fee 如何提交的？

### ISSUE THREAD

**Issue by fuyi501** [xuperchain/xuper-sdk-js#25]
交易需要消耗 fee，不过 postTransaction 好像并没有 fee 这个参数，fee 如何提交呢？

**Comment by SmilingXinyi** [comment]
可以看下这个链接，应该可以解决你的问题

[transfer](https://codesandbox.io/s/xuper-sdk-demo-q5m93?fontsize=14&hidenavigation=1&theme=dark&file=/src/index.js:1555-1595)
