### ISSUE TITLE
功能建议：增加一个xuper地址和evm地址转换的接口

### ISSUE THREAD

**Issue by CyrusLiu158** [xuperchain/xuper-sdk-js#32]
在利用solidity语言开发是，如ERC20、ERC721等，参数会经常传入以太坊0x的40位地址，这与xuper的16位地址不相同。
目前我是通过cli的形式在转换，既然cli已经支持，为什么sdk不加入该接口呢？

**Comment by uaanaa** [comment]
可以使用这个pr的版本：https://github.com/xuperchain/xuper-sdk-js/pull/27

**Comment by CyrusLiu158** [comment]
> #27

感谢
